namespace MailLoadTester;

public enum SmtpAuthMethod { Auto, Plain, Login, CramMd5, ScramSha1, Ntlm, OAuth2 }
public enum IpVersionPreference { Any, IPv4Only, IPv6Only, DualStack }

public sealed record MailTestOptions(
    string From,
    IReadOnlyList<string> Recipients,
    string SmtpHost,
    int Port,
    SmtpSecurity Security,
    bool UseAuthentication,
    string Username,
    string Password,
    int MessageCount,
    int IntervalMs,
    bool BatchMode,
    int BatchSize,
    int BatchPauseSeconds,
    int MaxConcurrency,
    string Subject,
    string Body,
    string DisplayName,
    bool RandomTestData,
    bool TestMode,
    string AllowedDomains,
    bool HtmlBody,
    IReadOnlyList<string> Attachments,
    IReadOnlyDictionary<string, string> CustomHeaders,
    bool IgnoreCertificateErrors,
    int MaxRetries,
    bool DryRun,
    bool UseSocks5Proxy = false,
    string ProxyHost = "",
    int ProxyPort = 1080,
    string ProxyUsername = "",
    string ProxyPassword = "",
    string ProxyList = "",
    bool ProxyListRandom = false,
    int ProxyBanMinutes = 15,
    bool DirectMxDelivery = false,
    bool PreWarmConnections = false,
    bool UseAdaptiveConcurrency = false,
    bool UseCircuitBreaker = false,
    int CircuitBreakerThreshold = 5,
    int CircuitBreakerWindowSize = 100,
    double CircuitBreakerFailurePercent = 90.0,
    bool EnableDashboard = false,
    int DashboardPort = 5000,
    SmtpAuthMethod AuthMethod = SmtpAuthMethod.Auto,
    string SourceIp = "",
    string Ipv6Prefix = "",
    int Ipv6PrefixLength = 64,
    string Ipv4Rotation = "",
    bool Ipv4RotationRandom = false,
    string ClientCertificatePath = "",
    string ClientCertificatePassword = "",
    IReadOnlyList<string>? BccRecipients = null,
    IReadOnlyList<string>? CcRecipients = null,
    bool SmtpUtf8 = false,
    IReadOnlyList<string>? InlineAttachments = null,
    string WebhookUrl = "",
    int BandwidthLimitKbps = 0,
    IpVersionPreference IpVersion = IpVersionPreference.Any,
    int ConnectTimeoutMs = 20000,
    int ReadTimeoutMs = 20000,
    bool EnableSessionLog = false,
    string SessionLogPath = "",
    bool AutoRestartOnFailure = false,
    int AutoRestartMaxAttempts = 3,
    string? EmlTemplatePath = null,
    int IdleConnectionHealthCheckSeconds = 30,
    bool UseBogusData = false,
    bool GenerateRandomHtml = false,
    bool GenerateRandomAttachments = false,
    int MaxRandomAttachments = 2,
    bool VarySubjectBodyPerMessage = false,
    int RandomAttachmentSizeMb = 0,
    string PaceProfile = "Standard",
    bool EnableJitter = true,
    int JitterPercent = 15,
    bool EnableBurstMode = false,
    int BurstSize = 10,
    int BurstPauseSeconds = 30,
    bool EnableProgressiveBackoff = true,
    int BackoffAfterSuccesses = 50,
    double BackoffMultiplier = 1.5,
    int MaxIntervalMs = 60_000,
    bool EnablePerRecipientLimit = false,
    int MaxMessagesPerRecipient = 20,
    int PerRecipientWindowMinutes = 60,
    bool EnableSendingTimeWindow = false,
    int SendingWindowFromHour = 8,
    int SendingWindowToHour = 18,
    bool EnableWarmup = false,
    string WarmupPhases = "50;150;500",
    bool DetectGreylist = true,
    int GreylistRetryMinutes = 10,
    int MaxGreylistRetries = 3,
    string ProviderPreset = "Custom",
    bool CheckRblBeforeStart = false,
    bool CollectObservedResponses = true,
    bool Unauthorized = false,
    IReadOnlyList<SmtpAccount>? Accounts = null,
    int DurationSeconds = 0);

public enum SmtpSecurity { None, StartTls, ImplicitTls }

public sealed record MailTestResult(
    int Requested,
    int Sent,
    int Failed,
    TimeSpan Elapsed,
    string LastError,
    double AvgLatencyMs,
    double MinLatencyMs,
    double MaxLatencyMs,
    double P50LatencyMs,
    double P95LatencyMs,
    double P99LatencyMs,
    double ThroughputPerSec,
    bool Cancelled = false,
    double ActiveThroughputPerSec = 0,
    int Retries = 0,
    int Smtp4xx = 0,
    int Smtp5xx = 0,
    int Timeouts = 0,
    int PoolConnections = 0,
    int AdaptiveConcurrency = 0,
    bool CircuitBreakerOpen = false,
    IReadOnlyList<string>? MxHosts = null,
    int AutoRestartAttempts = 0,
    string? SessionLogFile = null,
    double AvgPrepWaitMs = 0,
    double AvgAdaptiveWaitMs = 0,
    double AvgPoolWaitMs = 0,
    double AvgPaceWaitMs = 0,
    double AvgSmtpSendMs = 0,
    string? RunId = null,
    IReadOnlyList<EndpointHealthSnapshot>? EndpointHealth = null,
    ScenarioQueueMetricsSnapshot? QueueMetrics = null);
